### ISSUE TITLE
Problem with facade [4.1]?

### ISSUE THREAD

**Issue by cviebrock** [thomaswelton/laravel-facebook#5]
My controller contains:

``` php
    public function __construct( Facebook $facebook )
    {
        $this->facebook = $facebook;
    }

    public function getFacebook()
    {
        $params = array(
                'redirect_uri' => url('/login/fb/callback'),
                'scope'        => 'email',
        );
        return Redirect::to( $this->facebook->getLoginUrl($params) );
    }
```

Hitting the route for `getFacebook()` gives me:

```
Call to undefined method Thomaswelton\LaravelFacebook\Facades\Facebook::getLoginUrl()
```

I've got my `app/config/app.php` set up as instructed in the readme file.

I'm also wondering why your package requires `thomaswelton/facebook-php-sdk` and not `facebook/php-sdk`.  Does your fork add something to the "official" classes?

**Comment by thomaswelton** [comment]
The "official" php lib is/was not PSR-2 compatible and can not be autoloaded. Mine is a fork of a fork form a pull request submitted to facebook from someone else.

The issue you are having is because you are using dependency injection. You can access Facebook without DI as you should have included an alias in your app config.
If you want to use DI for testability then you can mock the facade from within your tests to achieve the same results.

I'll leave this open for now, but don't think this is a bug. Doing some googling this seems to be a common issue with using DI on a facade.

Thanks for using this lib and good luck :smile:

**Comment by cviebrock** [comment]
Yup, you're absolutely right about the DI vs Facade issue, so I'll close this myself.  Thanks!
